server:
  port: 8080
  error:
    include-message: always

server-url: http://localhost:8080
server-route:

database:
  host: localhost
  port: 5432
  username: task
  password: task
  database: task_management
  schema: task_management
  pool:
    maxIdleTimeInMinutes: 5
    maxSize: 30

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  jpa:
    properties:
    hibernate:
      jdbc:
        time_zone: UTC
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/task_management
    password: task
    user: task
    schemas: task_management
    out-of-order: true

springdoc:
  api-docs:
    enabled: true
    path: /task-management/doc/api-docs
  swagger-ui:
    enabled: true
    path: /task-management/doc/swagger-ui.html
    operationsSorter: alpha

